export const ANIMALS = [
  { name: 'Nyan cat', sprite: 'is-cat', trail: 'is-rainbow' },
  { name: 'Unicorn', sprite: 'is-unicorn', trail: 'is-sparkles' },
  { name: 'Dragon', sprite: 'is-dragon', trail: 'is-embers' },
  { name: 'Pig', sprite: 'is-pig', trail: 'is-hearts' },
  { name: 'Whale', sprite: 'is-whale', trail: 'is-bubbles' },
  { name: 'Fox', sprite: 'is-fox', trail: 'is-paws' },
  { name: 'Frog', sprite: 'is-frog', trail: 'is-dust' },
  { name: 'Penguin', sprite: 'is-penguin', trail: 'is-snow' },
  { name: 'Bee', sprite: 'is-bee', trail: 'is-honey' },
  { name: 'Owl', sprite: 'is-owl', trail: 'is-stars' },
  { name: 'Cow', sprite: 'is-cow', trail: 'is-daisies' },
  { name: 'Panda', sprite: 'is-panda', trail: 'is-bamboo' },
  { name: 'Red panda', sprite: 'is-red-panda', trail: 'is-leaves' },
  { name: 'Deer', sprite: 'is-deer', trail: 'is-acorns' },
  { name: 'Horse', sprite: 'is-horse', trail: 'is-clover' },
  { name: 'Sheep', sprite: 'is-sheep', trail: 'is-clouds' },
  { name: 'Hamster', sprite: 'is-hamster', trail: 'is-seeds' },
  { name: 'Giraffe', sprite: 'is-giraffe', trail: 'is-acacia' },
  { name: 'Hedgehog', sprite: 'is-hedgehog', trail: 'is-logomarks' },
];
