export interface SettingsRange {
  min: number;
  max?: number;
  exclusiveMin?: boolean;
  label?: string;
}

export const POSITIVE_NUMBER_RANGE: SettingsRange = Object.freeze({ min: 0, exclusiveMin: true, label: 'a positive number' });
export const NON_NEGATIVE_NUMBER_RANGE: SettingsRange = Object.freeze({ min: 0, label: 'zero or more' });

export const FLYING_ANIMALS_GAP_RANGE = Object.freeze({ min: 0, max: 300 });
export const FLYING_ANIMALS_DURATION_RANGE = Object.freeze({ min: 1, max: 60 });
export const FLYING_ANIMALS_SCALE_RANGE = Object.freeze({ min: 0.5, max: 2 });

export const REPLAY_BUFFER_KB_RANGE = Object.freeze({ min: 64, max: 16384 });


export const BRANCH_GC_STALE_DAYS_RANGE = POSITIVE_NUMBER_RANGE;
export const BRANCH_GC_INTERVAL_MS_RANGE = POSITIVE_NUMBER_RANGE;

export const VISIONS_QUIET_MS_RANGE = POSITIVE_NUMBER_RANGE;
export const VISIONS_COOLDOWN_MS_RANGE = POSITIVE_NUMBER_RANGE;
export const VISIONS_MAX_PER_HOUR_RANGE = POSITIVE_NUMBER_RANGE;
export const VISIONS_ACTIVITY_MAX_PER_HOUR_RANGE = NON_NEGATIVE_NUMBER_RANGE;
export const VISIONS_DISPATCH_TIMEOUT_RANGE = POSITIVE_NUMBER_RANGE;
export const VISIONS_INTENT_THREAD_TTL_MS_RANGE = POSITIVE_NUMBER_RANGE;

export const POSTHOG_INTERVAL_RANGE = POSITIVE_NUMBER_RANGE;
export const POSTHOG_MAX_CONCURRENT_RANGE = POSITIVE_NUMBER_RANGE;
export const POSTHOG_INVESTIGATION_TIMEOUT_RANGE = POSITIVE_NUMBER_RANGE;
export const POSTHOG_MIN_USERS_RANGE = POSITIVE_NUMBER_RANGE;
export const POSTHOG_ESCALATION_RANGE = POSITIVE_NUMBER_RANGE;
export const POSTHOG_RECURRENCE_WINDOW_RANGE = POSITIVE_NUMBER_RANGE;
export const POSTHOG_TRANSIENT_RECURRENCE_RANGE = POSITIVE_NUMBER_RANGE;
export const POSTHOG_FIX_TIMEOUT_RANGE = Object.freeze({ min: 60, max: 21600, label: 'between 60 and 21600' });
export const POSTHOG_TRAFFIC_MULTIPLIER_RANGE = Object.freeze({ min: 1, label: 'at least 1' });
export const POSTHOG_TRAFFIC_MIN_USERS_RANGE = Object.freeze({ min: 1, label: 'at least 1' });
export const POSTHOG_TRAFFIC_COOLDOWN_RANGE = NON_NEGATIVE_NUMBER_RANGE;
export const POSTHOG_TRAFFIC_BASELINE_RANGE = Object.freeze({ min: 1, max: 30, label: 'between 1 and 30' });

export const USAGE_SCAN_INTERVAL_RANGE = Object.freeze({ min: 1, max: 1440 });
export const USAGE_RETAIN_DAYS_RANGE = Object.freeze({ min: 1, max: 3650 });
export const USAGE_WAREHOUSE_RETAIN_DAYS_RANGE = Object.freeze({ min: 30, max: 3650 });
export const USAGE_SESSION_BLOCK_HOURS_RANGE = Object.freeze({ min: 1, max: 24 });
export const USAGE_BUDGET_RANGE = POSITIVE_NUMBER_RANGE;
export const USAGE_INTEGER_RANGES = Object.freeze({
  scanIntervalMinutes: USAGE_SCAN_INTERVAL_RANGE,
  retainDays: USAGE_RETAIN_DAYS_RANGE,
  warehouseRetainDays: USAGE_WAREHOUSE_RETAIN_DAYS_RANGE,
  sessionBlockHours: USAGE_SESSION_BLOCK_HOURS_RANGE,
});

export const CHANGE_MAP_NARRATOR_TIMEOUT_RANGE = Object.freeze({ min: 15, max: 600 });

export const SETTINGS_RANGES = Object.freeze({
  FLYING_ANIMALS_GAP_RANGE,
  FLYING_ANIMALS_DURATION_RANGE,
  FLYING_ANIMALS_SCALE_RANGE,
  CHANGE_MAP_NARRATOR_TIMEOUT_RANGE,
  POSTHOG_ESCALATION_RANGE,
  POSTHOG_FIX_TIMEOUT_RANGE,
  POSTHOG_INTERVAL_RANGE,
  POSTHOG_INVESTIGATION_TIMEOUT_RANGE,
  POSTHOG_MAX_CONCURRENT_RANGE,
  POSTHOG_MIN_USERS_RANGE,
  POSTHOG_TRAFFIC_BASELINE_RANGE,
  POSTHOG_TRAFFIC_COOLDOWN_RANGE,
  POSTHOG_TRAFFIC_MIN_USERS_RANGE,
  POSTHOG_TRAFFIC_MULTIPLIER_RANGE,
  REPLAY_BUFFER_KB_RANGE,
  USAGE_BUDGET_RANGE,
  USAGE_RETAIN_DAYS_RANGE,
  USAGE_SCAN_INTERVAL_RANGE,
  VISIONS_ACTIVITY_MAX_PER_HOUR_RANGE,
  VISIONS_COOLDOWN_MS_RANGE,
  VISIONS_DISPATCH_TIMEOUT_RANGE,
  VISIONS_INTENT_THREAD_TTL_MS_RANGE,
  VISIONS_MAX_PER_HOUR_RANGE,
  VISIONS_QUIET_MS_RANGE,
});
